// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddRequest(arg1:string,arg2:domain.RequestNode):Promise<void>;

export function CreateCollection(arg1:string):Promise<domain.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function DuplicateRequest(arg1:string,arg2:string):Promise<domain.RequestNode>;

export function ExecuteRequest(arg1:string,arg2:string):Promise<domain.ExecutionResult>;

export function GetCollection(arg1:string):Promise<domain.Collection>;

export function GetCollections():Promise<Array<domain.Collection>>;

export function ResolveVariable(arg1:string,arg2:Record<string, string>):Promise<string>;

export function UpdateCollection(arg1:domain.Collection):Promise<void>;

export function UpdateRequest(arg1:string,arg2:domain.RequestNode):Promise<void>;

export function ValidateVariables(arg1:string,arg2:Record<string, string>):Promise<Array<string>>;
