// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRequest(arg1, arg2) {
  return window['go']['main']['App']['AddRequest'](arg1, arg2);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function DuplicateRequest(arg1, arg2) {
  return window['go']['main']['App']['DuplicateRequest'](arg1, arg2);
}

export function ExecuteRequest(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRequest'](arg1, arg2);
}

export function ExportCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCollection'](arg1, arg2, arg3);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function ImportCollection(arg1) {
  return window['go']['main']['App']['ImportCollection'](arg1);
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function ResolveVariable(arg1, arg2) {
  return window['go']['main']['App']['ResolveVariable'](arg1, arg2);
}

export function UpdateCollection(arg1) {
  return window['go']['main']['App']['UpdateCollection'](arg1);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2);
}

export function ValidateVariables(arg1, arg2) {
  return window['go']['main']['App']['ValidateVariables'](arg1, arg2);
}
