// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateCollection(arg1:string):Promise<domain.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function GetCollection(arg1:string):Promise<domain.Collection>;

export function GetCollections():Promise<Array<domain.Collection>>;

export function UpdateCollection(arg1:domain.Collection):Promise<void>;
